services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn e_commerce.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0